### PR TITLE
added the offline google fonts

### PR DESCRIPTION
**Pull request by Nishant2907**
Added the `Montserrat` and `Fredericka` in the font.css and updated the index.html and user.html.
@sudo-rgorai  Kindly review it.

### CODE REVIEW

**Comment by sudo-rgorai** [comment]
Hey @Nishant2907 this is great! However there is still one small issue. I had asked you to delete the `fonts` folder. It seems you haven't done it yet. Other than that, LGTM :+1:

**Comment by Nishant2907** [comment]
Thanks so so i have to remove the fonts folder, or you could just add further fonts in it.

**Comment by sudo-rgorai** [comment]
Yes please delete the `fonts` folder and commit the changes. Then I shall merge the PR.

**Comment by Nishant2907** [comment]
hi @sudo-rgorai i have made the required changes, kindly hv a look at it.

**Comment by sudo-rgorai** [comment]
It seems correct now. Thanks for the help :smile:

**Pull request merged**
