### PR TITLE
minor style changes to search bar

### PR DESCRIPTION
**Pull request by Harshith2255**

### CODE REVIEW

**Comment by sudo-rgorai** [comment]
Hey @Harshith2255. The search bar looks relatively better. However, we can still improve it's design. As mentioned in the issue itself, you should try to mimic Google's original search bar:
Kazam_screenshot_00101

The reason why I'm emphasizing on this is because _familiarity adds value_. The new tab should _feel_ like home. And the google search bar is a very recognizable object.

How to achieve this?

1. Make the corners rounder. The extreme edges should feel like complete semi-circles! Currently your code does not really do that.
2. Ditch the search button. And place the search icon in the search bar itself.
3. Reduce inner font size.
4. Try to get rid of the border that you get on clicking the search bar.
5. Try making the background transparent and see if that looks good. This is a bit different from the original google search bar, but it may look nice with the dark background. This step is optional though, and you may skip it.

Thanks :relaxed:

**Comment by Harshith2255** [comment]
Okay sure

**Comment by Harshith2255** [comment]
> Hey @Harshith2255. The search bar looks relatively better. However, we can still improve it's design. As mentioned in the issue itself, you should try to mimic Google's original search bar:
> Kazam_screenshot_00101
> 
> The reason why I'm emphasizing on this is because _familiarity adds value_. The new tab should _feel_ like home. And the google search bar is a very recognizable object.
> 
> How to achieve this?
> 
> 1. Make the corners rounder. The extreme edges should feel like complete semi-circles! Currently your code does not really do that.
> 2. Ditch the search button. And place the search icon in the search bar itself.
> 3. Reduce inner font size.
> 4. Try to get rid of the border that you get on clicking the search bar.
> 5. Try making the background transparent and see if that looks good. This is a bit different from the original google search bar, but it may look nice with the dark background. This step is optional though, and you may skip it.
> 
> Thanks

**Comment by Harshith2255** [comment]
once check it now
i have made a new commit

**Comment by sudo-rgorai** [comment]
LGTM :+1:

**Pull request merged**
