### PR TITLE
README.md file updated 

### PR DESCRIPTION
**Pull request by astroidworld**
README.md file updated. The first image is updated. The image is now very much related to the current interface of the project.

### CODE REVIEW

**Comment by astroidworld** [comment]
please check the changes and tell me if anything is needed to do or if all are right then please merge it.

**Comment by astroidworld** [comment]
I am very much confused that do I need to change the link of the image of the readme file or not. please help me.

**Comment by sudo-rgorai** [comment]
There is no need to make any modifications in README. You can just take a screenshot of the window and replace `demo.png` in `assets/images/`. To make it clearer, you have to follow these steps:

1. Delete `demo.png` in `assets/images/`.
2. Take a screenshot of the the required page.
3. Save the screenshot in `assets/images/` and make sure you name it `demo.png`

Hope this makes it clear.

You may want to make a new PR as this one has a lot of junk commits. Thanks :relaxed:

**Comment by astroidworld** [comment]
Ok, understand. Thank you so much.

**Pull request closed without merging**
