### PR TITLE
Fixes issue #17

### PR DESCRIPTION
**Pull request by rahulk32**

### CODE REVIEW

**Comment by Godzilla5111** [comment]
Its nice @rahulk32 that you have removed all the logs from the script file. On an additional note, it would be nicer if you could remove unnecessary spaces from the code and prettified it a bit, which can be easily achieved using auto-indent feature/ third party packages in your text editor. Rest, LGTM👍.

**Comment by Godzilla5111** [comment]
I guess @sudo-rgorai, you can merge his PR in case you are satisfied with it👍

**Comment by Godzilla5111** [comment]
And ya, forgot to mention one thing, @rahulk32, always try to put up a short description describing the PR, even a one-liner would do fine👍 It may seem trivial but actually it proves to be a lot of help for those who are reviewing your code. Just keep that in mind.😉

**Comment by rahulk32** [comment]
> And ya, forgot to mention one thing, @rahulk32, always try to put up a short description describing the PR, even a one-liner would do fine👍 It may seem trivial but actually it proves to be a lot of help for those who are reviewing your code. Just keep that in mind.😉

Thanks for suggestion will keep that in mind from next time. Also what I am seeing in many repos that there are many issues in which people getting assigned themselves but they are not doing any PR in these should I try to resolve these issue or leave them.

**Comment by rahulk32** [comment]
> I guess @sudo-rgorai, you can merge his PR in case you are satisfied with it👍

If any more change you want I will add that

**Comment by Godzilla5111** [comment]
@rahulk32, it is not a hard and fast rule, but as per the moral code of conduct, the one who claims to work on the issue first gets it. And it is the PR of this person which generally gets accepted because most people don't claim issues which are already assigned to somebody else. These are some unsaid rules in Open Source. However, if the person remains inactive for a long duration after claiming an issue, it can be reassigned to someone else. It depends on the owner's will as well.  But in the end, the thing that matters the most is resolving the issues, no matter who resolves it😃🙌✌

**Comment by sudo-rgorai** [comment]
Some great points raised by @Godzilla5111. Yes, if your PR is related to an issue, it is often considered a good practice to discuss it on the issue thread before making the PR. When you're working on larger projects, things need to be very systematic to ensure proper maintenance of the codebase.

As far as this issue is concerned, I think #17 is resolved. I'll probably add another another issue later about detailed formatting when the code grows in size. Thanks for the help :smile:

**Pull request merged**
