### PR TITLE
Fix Issue #8 

### PR DESCRIPTION
**Pull request by Godzilla5111**
* Successfully implemented dynamic greetings.
* Reduced font size of greeting.

### CODE REVIEW

**Comment by sudo-rgorai** [comment]
Thanks for the PR. Looks great. :smile:

Just a suggestion. It seems you are working on master branch. Ideally, you should avoid working on master/main. This is because, there may be newer changes in upstream which you may want to pull to the master of your fork. If you are working on master, pulling these changes in _your_ master will be difficult. It is always preferred that you work on a feature branch and send a PR from that feature branch. This allows your master to easily sync with the upstream master. You can read the contribution guidelines for a good idea for the workflow.

Rest everything is awesome :+1:

**Comment by sudo-rgorai** [comment]
Also, I think it will be a bit odd to wish good evening at 11 PM or good morning at 1 AM. How about using `Sleep well, <user>.` between 10PM and 2 AM? Do you think we should do that?

**Comment by Godzilla5111** [comment]
Ya, we can do that! But what do say, night owls exist😁! They won't sleep even after seeing such messages.😂(P.S I am one of those😜). Some people like to work during night time. And for those who sleep at that time, they won't have their browser open, isn't it? As far as momentum is concerned, it works the same. It wishes good morning at timings as odd as 2 or 3 am, basically anything after midnight is morning by definition. But what's the fun in being conventional? We can surely try this. Rest, I leave it upon you. I will make the changes as per your suggestions, or else you can merge the PR if you are satisfied. What do you say?

**Comment by sudo-rgorai** [comment]
True! Extensions like momentum show these off-timed messages while other extensions like tabliss show sleep well/good night messages which may seem odd to a lot of people. How about using a neutral greeting for this time slot? `Hi <user>` or `Welcome back <user>`?

**Comment by Godzilla5111** [comment]
Ya! That would be nice to show neutral messages at odd timings. I will do that. Please confirm between what timings should I display the neutral messages, and then I will proceed as directed.

**Comment by sudo-rgorai** [comment]
Great! Since there's no preferred timing for such messages, I think we can extend the slot from 8PM to 4AM. Does that sound good?

**Comment by Godzilla5111** [comment]
Yes👍 That would be great! Then I will do the correction and get back to you👍 Cheers!

**Comment by Godzilla5111** [comment]
Hey @sudo-rgorai , please review the changes and merge the PR now👍

**Comment by sudo-rgorai** [comment]
LGTM :+1:

**Pull request merged**
